apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lcp-prod
resources:
  - ../../k8s
  - status-ingress.yaml
images:
  - name: registry.example.com/lcp/lcp-server
    newName: registry.testmedical.ir:5000/lcp-server
    newTag: prod-v24
  - name: registry.example.com/lcp/lcp-server-core
    newName: registry.testmedical.ir:5000/lcp-server
    newTag: prod-v24
  - name: registry.example.com/lcp/lcp-admin-ui
    newName: registry.testmedical.ir:5000/lcp-admin-ui
    newTag: prod-v24
labels:
  - pairs:
      environment: prod
patches:
  - path: patch-deployments.yaml
  - path: patch-configmap.yaml
  - path: patch-ingress.yaml
  - path: patch-hpa.yaml
  - path: patch-resources.yaml
