apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lcp-server
  labels:
    app: lcp-server
spec:
  podSelector:
    matchLabels:
      app: lcp-server
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: lcp-core
      ports:
        - protocol: TCP
          port: 8989
    - to:
        - podSelector:
            matchLabels:
              app: lsd-core
      ports:
        - protocol: TCP
          port: 8990
    - ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    - ports:
        - protocol: TCP
          port: 5432
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 80
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
