profile: "basic"
lcp_update_auth:
  username: "admin"
  password: "admin_pass"
lsd_notify_auth:
  username: "admin"
  password: "admin_pass"
cms_access_auth:
  username: ""
  password: ""
lcp:
  host: "0.0.0.0"
  public_base_url: "http://127.0.0.1:8989"
lsd:
  host: "0.0.0.0"
  port: 8990
  public_base_url: "http://127.0.0.1:8990"
  database: "sqlite3://file:/srv/readium/data/lsd.sqlite?cache=shared&mode=rwc"
  auth_file: "/srv/readium/config/htpasswd"
  license_link_url: "http://127.0.0.1:8990/licenses/{license_id}"
  user_data_url: "http://lcp-server:8080/api/v1/licenses/{license_id}/user"
license_status:
  register: true
