apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - prometheus.monitoring.svc.cluster.local:9090

      - job_name: lcp-server-dev
        metrics_path: /metrics
        static_configs:
          - targets:
              - lcp-server.lcp-dev.svc.cluster.local:80

      - job_name: lcp-server-staging
        metrics_path: /metrics
        static_configs:
          - targets:
              - lcp-server.lcp-staging.svc.cluster.local:80

      - job_name: lcp-server-prod
        metrics_path: /metrics
        static_configs:
          - targets:
              - lcp-server.lcp-prod.svc.cluster.local:80

      - job_name: node
        static_configs:
          - targets:
              - node-exporter.monitoring.svc.cluster.local:9100
