apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lcp-prod
  namespace: argocd
spec:
  project: lcp
  source:
    repoURL: https://github.com/amirhdev/ebook-lcp-server.git
    targetRevision: main
    path: deploy/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: lcp-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
